-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT A.ITEM_ID FROM ITEM_INFO I
    JOIN ITEM_TREE A ON I.ITEM_ID = A.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;